version: "3.9"
services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
